[package]
name = "tokio_test"
version = "0.1.0"
authors = ["hevienz <hevienz@qq.com>"]

[dependencies]
tokio = "0.1.7"
tokio-io = "0.1.7"
bytes = "0.4"
futures = "0.1.21"
log = "0.4.2"
pretty_env_logger = "0.2"
